---
mgt:
  vars:
    apache_package_name:         httpd
    apache_backend_server_host:  sunstone.mydomain
    apache_backend_server_port:  9869

  hosts:
    mgt1.mydomain:
      ipv4_addresses:
        - 192.168.123.31  # interface on the management network

one:
  vars:
    gluster_block_device:           /dev/vdb
    gluster_volume_name:            datastore1
    gluster_auth_allow:             192.168.124.*
    gluster_interface_name:         eth2
    gluster_server_node:            one1.mydomain  # the node used for administration of the cluster
    gluster_replace_node:           null  # node to be replaced
    gluster_replace_uuid:           null  # UUID of the node to be replaced
    gluster_volume_id:              null  # ID of the gluster_volume_name gluster volume
    opennebula_version:             5.4
    opennebula_ha_leader:           one1.mydomain
    opennebula_ha_follower:         one2.mydomain
    opennebula_ha_floating_ip:      192.168.123.10
    opennebula_ha_floating_ip_cidr: 24
    opennebula_ha_interface_name:   br1
    oneadmin_password:              password

  hosts:
    one1.mydomain:
      ipv4_addresses:
        - 192.168.123.11  # interface on the management network, used also for opennebula bridge
        - 192.168.124.11  # interface used by glusterfs
    one2.mydomain:
      ipv4_addresses:
        - 192.168.123.12  # interface on the management network, used also for opennebula bridge
        - 192.168.124.12  # interface used by glusterfs
    one3.mydomain:
      ipv4_addresses:
        - 192.168.123.13  # interface on the management network, used also for opennebula bridge
        - 192.168.124.13  # interface used by glusterfs
